#!/usr/bin/env node
/**
 * build-cursor.mjs — one-way generator: Claude Code plugin skills → Cursor Plugins.
 *
 * The Claude plugins under `plugins/<p>/skills/<s>/` are the SINGLE SOURCE OF TRUTH.
 * This script emits installable Cursor plugins under `platforms/cursor/<p>/` (flattened
 * skill folders `nav-audit`, not bare `audit` — Cursor does not namespace plugin skills)
 * plus a repo-root `.cursor-plugin/marketplace.json`. Re-run after any skill edit; never
 * hand-edit the generated output.
 *
 *   node scripts/build-cursor.mjs              # generate
 *   node scripts/build-cursor.mjs --sync-local # generate + symlink into ~/.cursor/plugins/local
 */
import {
  readFileSync,
  writeFileSync,
  readdirSync,
  mkdirSync,
  rmSync,
  existsSync,
  statSync,
  lstatSync,
  cpSync,
  symlinkSync,
} from "node:fs";
import { join, dirname, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { homedir } from "node:os";
import {
  createCursorGuidanceLowerer,
  injectCursorBrowserVerifyContract,
  injectCursorInteractiveChoiceContract,
  lowerCursorBrowserVerifyProse,
  lowerCursorFrontmatter,
  lowerCursorInteractiveChoiceProse,
  lowerCursorWorkerProse,
} from "./lib/cursor-compat.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const PLUGINS_DIR = join(ROOT, "plugins");
const OUT_ROOT = join(ROOT, "platforms", "cursor");
const MARKETPLACE_DIR = join(ROOT, ".cursor-plugin");
const MARKETPLACE_JSON = join(MARKETPLACE_DIR, "marketplace.json");
const CLAUDE_MARKETPLACE = join(ROOT, ".claude-plugin", "marketplace.json");
const CURSOR_MANIFEST = join(OUT_ROOT, "manifest.json");
const DESCRIPTION_HARD_LIMIT = 1024;
const GEN_BANNER =
  "<!-- GENERATED by scripts/build-cursor.mjs from plugins/{plugin}/skills/{skill}/ — do not hand-edit; re-run the generator. -->\n";
const LEGACY_LOCAL_NAMES = ["think", "research"];
const RECEIPT_NAME = ".skills-marketplace-receipt.json";

const PLUGINS = readdirSync(PLUGINS_DIR)
  .filter((plugin) => {
    const pluginDir = join(PLUGINS_DIR, plugin);
    return (
      statSync(pluginDir).isDirectory() &&
      existsSync(join(pluginDir, "CLAUDE.md")) &&
      existsSync(join(pluginDir, "skills"))
    );
  })
  .sort();

const SKILLS = [
  ...new Set(
    PLUGINS.flatMap((plugin) =>
      readdirSync(join(PLUGINS_DIR, plugin, "skills")).filter((skill) =>
        statSync(join(PLUGINS_DIR, plugin, "skills", skill)).isDirectory(),
      ),
    ),
  ),
].sort();

const GUIDANCE = createCursorGuidanceLowerer({ plugins: PLUGINS, skills: SKILLS });

function walk(dir) {
  const out = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(path));
    else out.push(path);
  }
  return out;
}

function toJson(value) {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function parseFrontmatterString(raw) {
  try {
    const parsed = JSON.parse(raw);
    return typeof parsed === "string" ? parsed : raw;
  } catch {
    return raw;
  }
}

function renameFrontmatter(text, bare, flat) {
  return text.replace(new RegExp(`^name:\\s*${bare}\\s*$`, "m"), `name: ${flat}`);
}

function normalizeCursorDescription(text) {
  return text.replace(/^---\n([\s\S]*?)\n---/, (_match, frontmatter) => {
    const normalized = frontmatter.replace(/^description:\s*(.*)$/m, (_line, rawDescription) => {
      let description = parseFrontmatterString(rawDescription.trim()).replace(/\s+/g, " ").trim();
      if (description.length > DESCRIPTION_HARD_LIMIT) {
        description = `${description.slice(0, DESCRIPTION_HARD_LIMIT - 3).trimEnd()}...`;
      }
      return `description: ${JSON.stringify(description)}`;
    });
    return `---\n${normalized}\n---`;
  });
}

function compileSkillMarkdown(rawText, { plugin, skill, flat }) {
  let text = renameFrontmatter(rawText, skill, flat);
  text = GUIDANCE.lowerSkillGuidance(text, { plugin, skill });
  text = lowerCursorFrontmatter(text);
  text = lowerCursorWorkerProse(text);
  text = lowerCursorInteractiveChoiceProse(text);
  text = lowerCursorBrowserVerifyProse(text);
  text = injectCursorInteractiveChoiceContract(text, flat);
  text = injectCursorBrowserVerifyContract(text, flat);
  text = normalizeCursorDescription(text);
  const banner = GEN_BANNER.replace("{plugin}", plugin).replace("{skill}", skill);
  return text.replace(/^(---\n[\s\S]*?\n---\n)/, `$1${banner}`);
}

function compileSkillReferenceText(rawText, { plugin, skill }) {
  return lowerCursorBrowserVerifyProse(
    lowerCursorInteractiveChoiceProse(
      lowerCursorWorkerProse(GUIDANCE.lowerSkillGuidance(rawText, { plugin, skill })),
    ),
  );
}

function compilePluginExtraText(rawText, plugin) {
  return lowerCursorBrowserVerifyProse(
    lowerCursorInteractiveChoiceProse(
      lowerCursorWorkerProse(GUIDANCE.lowerPluginExtraGuidance(rawText, plugin)),
    ),
  );
}

function readOwnerManifest(plugin) {
  return JSON.parse(readFileSync(join(PLUGINS_DIR, plugin, ".claude-plugin", "plugin.json"), "utf8"));
}

function writeCursorPluginManifest(pluginDir, owner) {
  mkdirSync(join(pluginDir, ".cursor-plugin"), { recursive: true });
  writeFileSync(
    join(pluginDir, ".cursor-plugin", "plugin.json"),
    toJson({
      name: owner.name,
      version: owner.version,
      description: owner.description,
      author: owner.author,
    }),
  );
}

function emitPluginExtras(plugin, outPluginDir) {
  const srcPluginDir = join(PLUGINS_DIR, plugin);
  for (const extra of ["agents", "references", "assets", "scripts"]) {
    const src = join(srcPluginDir, extra);
    if (!existsSync(src)) continue;
    const dest = join(outPluginDir, extra);
    cpSync(src, dest, { recursive: true });
    for (const file of walk(dest)) {
      if (/\.(md|html|txt)$/.test(file)) {
        writeFileSync(file, compilePluginExtraText(readFileSync(file, "utf8"), plugin));
      }
    }
  }
}

function emitSkills(plugin, outPluginDir) {
  const skillsDir = join(PLUGINS_DIR, plugin, "skills");
  const emitted = [];
  for (const skill of readdirSync(skillsDir).sort()) {
    const srcSkillDir = join(skillsDir, skill);
    if (!statSync(srcSkillDir).isDirectory()) continue;
    const srcSkillMd = join(srcSkillDir, "SKILL.md");
    if (!existsSync(srcSkillMd)) continue;

    const flat = `${plugin}-${skill}`;
    const outSkillDir = join(outPluginDir, "skills", flat);
    mkdirSync(outSkillDir, { recursive: true });
    writeFileSync(
      join(outSkillDir, "SKILL.md"),
      compileSkillMarkdown(readFileSync(srcSkillMd, "utf8"), { plugin, skill, flat }),
    );

    for (const sub of ["references", "assets", "scripts"]) {
      const srcSub = join(srcSkillDir, sub);
      if (!existsSync(srcSub)) continue;
      const outSub = join(outSkillDir, sub);
      cpSync(srcSub, outSub, { recursive: true });
      for (const file of walk(outSub)) {
        if (/\.(md|html|txt)$/.test(file)) {
          writeFileSync(file, compileSkillReferenceText(readFileSync(file, "utf8"), { plugin, skill }));
        }
      }
    }
    emitted.push(flat);
  }
  return emitted;
}

function writeMarketplace(owners) {
  const claude = JSON.parse(readFileSync(CLAUDE_MARKETPLACE, "utf8"));
  const descriptionByName = new Map((claude.plugins ?? []).map((entry) => [entry.name, entry.description]));
  mkdirSync(MARKETPLACE_DIR, { recursive: true });
  writeFileSync(
    MARKETPLACE_JSON,
    toJson({
      name: claude.name ?? "skills",
      owner: { name: claude.owner?.name ?? "Paul" },
      metadata: {
        description:
          "Paul's skills marketplace — native Cursor Plugins generated from the Claude source under plugins/.",
        pluginRoot: "platforms/cursor",
      },
      plugins: owners.map((owner) => ({
        name: owner.name,
        source: owner.name,
        description: descriptionByName.get(owner.name) ?? owner.description,
        version: owner.version,
      })),
    }),
  );
}

function build() {
  mkdirSync(OUT_ROOT, { recursive: true });
  const owners = [];
  const emitted = [];

  for (const plugin of PLUGINS) {
    const owner = readOwnerManifest(plugin);
    owners.push(owner);
    const outPluginDir = join(OUT_ROOT, plugin);
    if (existsSync(outPluginDir)) rmSync(outPluginDir, { recursive: true });
    mkdirSync(outPluginDir, { recursive: true });
    writeCursorPluginManifest(outPluginDir, owner);
    emitPluginExtras(plugin, outPluginDir);
    emitted.push(...emitSkills(plugin, outPluginDir));
  }

  for (const entry of readdirSync(OUT_ROOT)) {
    if (entry === "manifest.json") continue;
    if (!PLUGINS.includes(entry)) {
      rmSync(join(OUT_ROOT, entry), { recursive: true, force: true });
    }
  }

  writeMarketplace(owners);
  console.log(`✓ ${emitted.length} Cursor skills → platforms/cursor/<plugin>/skills/  (${emitted.join(", ")})`);
  console.log(`✓ .cursor-plugin/marketplace.json (${owners.map((o) => o.name).join(", ")})`);
  return { owners, emitted };
}

function readReceipt(localDir) {
  const path = join(localDir, RECEIPT_NAME);
  if (!existsSync(path)) return { plugins: [] };
  try {
    return JSON.parse(readFileSync(path, "utf8"));
  } catch {
    return { plugins: [] };
  }
}

function adapterRelease() {
  if (!existsSync(CURSOR_MANIFEST)) return "0.0.0";
  try {
    return JSON.parse(readFileSync(CURSOR_MANIFEST, "utf8")).adapter_release ?? "0.0.0";
  } catch {
    return "0.0.0";
  }
}

function pathExists(path) {
  try {
    lstatSync(path);
    return true;
  } catch {
    return false;
  }
}

function replaceSymlink(dest, target) {
  if (pathExists(dest)) rmSync(dest, { recursive: true, force: true });
  symlinkSync(target, dest);
}

function overlappingAgentsSkills(emitted) {
  const agentsRoot = join(homedir(), ".agents", "skills");
  if (!existsSync(agentsRoot)) return [];
  return emitted.filter((flat) => existsSync(join(agentsRoot, flat, "SKILL.md")));
}

function syncLocal({ emitted }) {
  const localDir = join(homedir(), ".cursor", "plugins", "local");
  mkdirSync(localDir, { recursive: true });
  const previous = new Set([...(readReceipt(localDir).plugins ?? []), ...LEGACY_LOCAL_NAMES]);
  const current = new Set(PLUGINS);

  for (const name of previous) {
    if (current.has(name)) continue;
    const stale = join(localDir, name);
    if (pathExists(stale)) rmSync(stale, { recursive: true, force: true });
  }

  for (const plugin of PLUGINS) {
    replaceSymlink(join(localDir, plugin), join(OUT_ROOT, plugin));
  }

  writeFileSync(
    join(localDir, RECEIPT_NAME),
    toJson({
      adapter_release: adapterRelease(),
      plugins: PLUGINS,
      source: ROOT,
      generated: relative(ROOT, OUT_ROOT),
    }),
  );

  console.log(`✓ Symlinked ${PLUGINS.length} Cursor plugins → ${localDir}`);
  console.log("  Reload Cursor (Developer: Reload Window) then type / and search nav-audit.");

  const overlap = overlappingAgentsSkills(emitted);
  if (overlap.length) {
    console.warn("\n⚠ Cursor also loads ~/.agents/skills. These flattened names overlap the new plugins:");
    console.warn(`  ${overlap.join(", ")}`);
    console.warn("  Duplicate names can hide a skill from the slash menu.");
    console.warn("  Dual-global (Cursor plugins + Codex everywhere, no shared names):");
    console.warn("    node scripts/build-codex.mjs --sync-global --profile all --global-root codex");
    console.warn('  Then in Cursor Settings → Rules, Skills, Subagents: turn OFF');
    console.warn('  "Include third-party Plugins, Skills, and other configs"');
    console.warn("  so Cursor does not also load ~/.codex/skills.");
  }
}

const { owners, emitted } = build();
void owners;
if (process.argv.includes("--sync-local")) syncLocal({ emitted });
