#!/usr/bin/env node
/**
 * build-codex.mjs — one-way generator: Claude Code plugin skills → Codex Agent Skills (★).
 *
 * The Claude plugins under `plugins/<p>/skills/<s>/` are the SINGLE SOURCE OF TRUTH.
 * This script emits a Codex-discoverable mirror under `.agents/skills/<p>-<s>/` plus a
 * repo-root `AGENTS.md` synthesised from plugin `CLAUDE.md` files. Re-run after any
 * skill edit; never hand-edit the generated output (it is overwritten).
 *
 * This file owns ONLY filesystem discovery/copy/walk plus writing generated destinations.
 * Every Codex-specific text transform (frontmatter lowering, interactive-choice/browser-verify/
 * worker-dispatch contracts, browser runtime-ownership lowering, project-guidance/namespace
 * rewrites, the unsupported-token scan)
 * lives in scripts/lib/codex-compat.mjs — the compiler this script calls once per file. See
 * blueprints/plans/2026-07-13-codex-compatibility.md Phases 1-4.
 *
 * Reads: node:fs · node:path (plugins/ tree · plugins/<p>/CLAUDE.md)
 */
import { readFileSync, writeFileSync, readdirSync, mkdirSync, rmSync, existsSync, statSync, cpSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import {
  codexDescription,
  findInstalledSkillCopies,
  loadCodexProjection,
  selectProfile,
} from "./lib/codex-projection.mjs";
import {
  createProjectGuidanceLowerer,
  detectUnsupported,
  injectBrowserVerifyContract,
  injectInteractiveChoiceContract,
  injectSessionOpenContract,
  injectWorkerDispatchContract,
  lowerBrowserVerifyProse,
  lowerFrontmatter,
  lowerInteractiveChoiceProse,
  lowerSessionOpenProse,
  lowerWorkerProse,
} from "./lib/codex-compat.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const PLUGINS_DIR = join(ROOT, "plugins");
const OUT_DIR = join(ROOT, ".agents", "skills");
const CODEX_AGENTS_DIR = join(ROOT, ".codex", "agents");
const CODEX_HOOKS_DIR = join(ROOT, ".codex", "hooks");
const CODEX_HOOKS_CONFIG = join(ROOT, ".codex", "hooks.json");
const AGENTS_MD = join(ROOT, "AGENTS.md");
const BROWSER_VERIFIER_SOURCE = join(ROOT, "plugins", "shape", "agents", "browser-verifier.md");
const BROWSER_VERIFIER_DEST = join(CODEX_AGENTS_DIR, "browser-verifier.toml");
const CODEX_HOOKS_SOURCE_DIR = join(ROOT, "platforms", "codex", "hooks");
const CODEX_HOOKS_CONFIG_SOURCE = join(CODEX_HOOKS_SOURCE_DIR, "hooks.json");
const PROJECTION = loadCodexProjection(ROOT);
const SESSION_START_HOOK_COMMAND = "node .codex/hooks/relay-digest-session-start.mjs";
const BROWSER_VERIFIER_DESCRIPTION_OLD =
  "Runs on a cheap model and keeps image tokens out of the caller's context.";
const BROWSER_VERIFIER_DESCRIPTION_NEW =
  "Runs in the configured mechanical-tier executor role and keeps image tokens out of the caller’s context.";

const PLUGINS = readdirSync(PLUGINS_DIR)
  .filter((plugin) => {
    const pluginDir = join(PLUGINS_DIR, plugin);
    return (
      statSync(pluginDir).isDirectory() &&
      existsSync(join(pluginDir, "CLAUDE.md")) &&
      existsSync(join(pluginDir, "skills"))
    );
  })
  .sort();
const SKILLS = [
  ...new Set(
    PLUGINS.flatMap((plugin) =>
      readdirSync(join(PLUGINS_DIR, plugin, "skills")).filter((skill) =>
        statSync(join(PLUGINS_DIR, plugin, "skills", skill)).isDirectory(),
      ),
    ),
  ),
].sort();
const GUIDANCE = createProjectGuidanceLowerer({ plugins: PLUGINS, skills: SKILLS });
const CODEX_DESCRIPTION_HARD_LIMIT = 1024;

/** Bump the frontmatter `name:` to the flattened Codex name (first occurrence only). */
function renameFrontmatter(text, bare, flat) {
  return text.replace(new RegExp(`^name:\\s*${bare}\\s*$`, "m"), `name: ${flat}`);
}

/**
 * Codex validates metadata more strictly than Claude plugins do. The projection sidecar
 * supplies the normal budget; this hard limit remains a final format-safety backstop.
 */
function normalizeCodexFrontmatter(text, flatName) {
  return text.replace(/^---\n([\s\S]*?)\n---/, (_match, frontmatter) => {
    const normalized = frontmatter.replace(/^description:\s*(.*)$/m, (_line, rawDescription) => {
      const sourceDescription = parseFrontmatterString(rawDescription.trim()).replace(/\s+/g, " ").trim();
      let description = codexDescription(PROJECTION, flatName, sourceDescription);
      if (description.length > CODEX_DESCRIPTION_HARD_LIMIT) {
        description = `${description.slice(0, CODEX_DESCRIPTION_HARD_LIMIT - 3).trimEnd()}...`;
      }
      return `description: ${JSON.stringify(description)}`;
    });
    return `---\n${normalized}\n---`;
  });
}

function parseFrontmatterString(raw) {
  try {
    const parsed = JSON.parse(raw);
    return typeof parsed === "string" ? parsed : raw;
  } catch {
    return raw;
  }
}

const GEN_BANNER_SKILL = "<!-- GENERATED by scripts/build-codex.mjs from plugins/{plugin}/skills/{skill}/ — do not hand-edit; re-run the generator. -->\n";

/**
 * The Codex compiler pipeline for one SKILL.md: rename → project-guidance lowering (namespace
 * flatten, reference reroot, CLAUDE.md→AGENTS.md, /init softening) → frontmatter lowering
 * (strip model:sonnet/disable-model-invocation, inject the Codex-side instruction) → worker-prose
 * lowering (Agent/subagent_type/sub-agent constructs + remaining prose mentions of the two
 * stripped frontmatter fields) → interactive-choice prose lowering (all profiles) →
 * browser-runtime prose lowering (Phase 4, precise runtime/path claims only) →
 * session-open prose lowering (Phase 4, precise startup/resume hook wording only) →
 * interactive-choice contract injection (Phase 3, nine consumers) → browser-verify
 * contract injection (Phase 4, three consumers) → session-open contract injection
 * (Phase 4, relay-digest only) → worker-dispatch contract injection (Phase 2,
 * dispatch-heavy skills only) → Codex description-budget normalization →
 * generated banner.
 */
function compileSkillMarkdown(rawText, { plugin, skill, flat }) {
  let text = renameFrontmatter(rawText, skill, flat);
  text = GUIDANCE.lowerSkillGuidance(text);
  const { text: withoutFrontmatterFields } = lowerFrontmatter(text);
  text = lowerWorkerProse(withoutFrontmatterFields);
  text = lowerInteractiveChoiceProse(text);
  text = lowerBrowserVerifyProse(text);
  text = lowerSessionOpenProse(text);
  text = injectInteractiveChoiceContract(text, flat);
  text = injectBrowserVerifyContract(text, flat);
  text = injectSessionOpenContract(text, flat);
  text = injectWorkerDispatchContract(text, flat);
  text = normalizeCodexFrontmatter(text, flat);
  const banner = GEN_BANNER_SKILL.replace("{plugin}", plugin).replace("{skill}", skill);
  text = text.replace(/^(---\n[\s\S]*?\n---\n)/, `$1${banner}`);
  return text;
}

/** Reference/asset text files (*.md/*.html/*.txt) travel with a skill dir: same project-guidance
 * + worker-prose lowering, no frontmatter (they don't have any) and no banner (the skill's own
 * SKILL.md banner already marks the directory as generated). */
function compileReferenceText(rawText) {
  return lowerSessionOpenProse(
    lowerBrowserVerifyProse(
      lowerInteractiveChoiceProse(lowerWorkerProse(GUIDANCE.lowerSkillGuidance(rawText))),
    ),
  );
}

function compileScriptText(rawText) {
  return lowerSessionOpenProse(rawText);
}

function build() {
  if (existsSync(OUT_DIR)) rmSync(OUT_DIR, { recursive: true });
  mkdirSync(OUT_DIR, { recursive: true });
  mkdirSync(CODEX_AGENTS_DIR, { recursive: true });
  mkdirSync(CODEX_HOOKS_DIR, { recursive: true });

  const emitted = [];
  for (const plugin of PLUGINS) {
    const skillsDir = join(PLUGINS_DIR, plugin, "skills");
    if (!existsSync(skillsDir)) continue;
    for (const skill of readdirSync(skillsDir)) {
      const srcSkillDir = join(skillsDir, skill);
      if (!statSync(srcSkillDir).isDirectory()) continue;
      const srcSkillMd = join(srcSkillDir, "SKILL.md");
      if (!existsSync(srcSkillMd)) continue;

      const flat = `${plugin}-${skill}`;
      const outSkillDir = join(OUT_DIR, flat);
      mkdirSync(outSkillDir, { recursive: true });

      const md = compileSkillMarkdown(readFileSync(srcSkillMd, "utf8"), { plugin, skill, flat });
      writeFileSync(join(outSkillDir, "SKILL.md"), md);

      // Bundled resources (references/, assets/, scripts/): copy verbatim, compiling *.md/*.html/*.txt.
      for (const sub of ["references", "assets", "scripts"]) {
        const srcSub = join(srcSkillDir, sub);
        if (!existsSync(srcSub)) continue;
        const outSub = join(outSkillDir, sub);
        cpSync(srcSub, outSub, { recursive: true });
        for (const f of walk(outSub)) {
          if (/\.(md|html|txt)$/.test(f)) writeFileSync(f, compileReferenceText(readFileSync(f, "utf8")));
          if (/\.mjs$/.test(f)) writeFileSync(f, compileScriptText(readFileSync(f, "utf8")));
        }
      }
      emitted.push(flat);
    }
  }

  buildAgentsMd();
  buildBrowserVerifierAgent();
  buildHooks();
  reportUnsupported(emitted);
  console.log(`✓ ${emitted.length} Codex skills → .agents/skills/  (${emitted.join(", ")})`);
  console.log(`✓ AGENTS.md (from CLAUDE.md + ${PLUGINS.map((p) => `plugins/${p}/CLAUDE.md`).join(" + ")})`);
  console.log(`✓ .codex/agents/browser-verifier.toml (from plugins/shape/agents/browser-verifier.md)`);
  console.log(`✓ .codex/hooks.json + .codex/hooks/* (from platforms/codex/hooks/)`);
}

/** Synthesise repo-root AGENTS.md: the repo-root CLAUDE.md (repo-wide rules) + each plugin's CLAUDE.md.
 * Same project-guidance + worker-prose lowering as skill bodies, so AGENTS.md never leaks
 * `model: sonnet` / `disable-model-invocation` prose describing the authoring convention itself. */
function buildAgentsMd() {
  const preamble = [
    "# AGENTS.md — `skills` marketplace",
    "",
    "<!-- GENERATED by scripts/build-codex.mjs from CLAUDE.md + plugins/*/CLAUDE.md — do not hand-edit; re-run the generator. -->",
    "",
    "> Context for an agent working in **this repo**. The source of truth is the Claude Code plugins under",
    "> `plugins/<plugin>/skills/<skill>/SKILL.md`. Their Codex mirror lives in `.agents/skills/<plugin>-<skill>/`",
    "> (flat, unnamespaced — Codex has no plugin namespace) and is **generated** by `scripts/build-codex.mjs`.",
    "> Edit the plugin skills, then re-run the generator; never hand-edit `.agents/skills/` or this file.",
    "",
    "Each `SKILL.md` is self-contained (it restates the rules it needs). The repo-wide rules for editing this",
    "marketplace follow (mirrored from the repo-root `CLAUDE.md`), then each plugin's own conventions.",
  ].join("\n");

  let rootRules = readFileSync(join(ROOT, "CLAUDE.md"), "utf8");
  rootRules = lowerBrowserVerifyProse(
    lowerInteractiveChoiceProse(
      lowerWorkerProse(
        GUIDANCE.lowerSharedGuidance(rootRules.replace(/^#\s+CLAUDE\.md.*$/m, "# marketplace — repo-wide rules (editing this repo)")),
      ),
    ),
  );
  rootRules = lowerSessionOpenProse(rootRules);

  const sections = PLUGINS.map((plugin) => {
    let body = readFileSync(join(PLUGINS_DIR, plugin, "CLAUDE.md"), "utf8");
    body = body.replace(/^#\s+.*plugin-level CLAUDE\.md\s*$/m, `# ${plugin} — plugin conventions`);
    return lowerSessionOpenProse(
      lowerBrowserVerifyProse(
        lowerInteractiveChoiceProse(lowerWorkerProse(GUIDANCE.lowerSharedGuidance(body))),
      ),
    );
  });

  writeFileSync(AGENTS_MD, [preamble, rootRules, ...sections].join("\n\n---\n\n") + "\n");
}

/** Informational only (never fails the build): summarizes any denylisted-token categories still
 * present in generated output. Uses the same manifest-driven rule list the validator's
 * --compat-audit door reports in full; this is just a quick per-build signal. */
function reportUnsupported(emittedFlats) {
  const counts = new Map();
  const skillMd = emittedFlats.map((flat) => join(OUT_DIR, flat, "SKILL.md"));
  const generatedRoots = [AGENTS_MD, BROWSER_VERIFIER_DEST];
  for (const file of [...skillMd, ...generatedRoots]) {
    if (!existsSync(file)) continue;
    const rel = file.replace(`${ROOT}/`, "");
    const findings = detectUnsupported(ROOT, rel, readFileSync(file, "utf8"));
    for (const finding of findings) counts.set(finding.category, (counts.get(finding.category) || 0) + 1);
  }
  if (!counts.size) return;
  const summary = [...counts.entries()].sort().map(([id, n]) => `${id}=${n}`).join(", ");
  console.log(`  (remaining denylisted-token categories: ${summary})`);
}

function buildBrowserVerifierAgent() {
  const raw = readFileSync(BROWSER_VERIFIER_SOURCE, "utf8");
  const { frontmatter, body } = splitFrontmatter(raw);
  const name = frontmatter.name;
  const description = lowerBrowserVerifierDescription(parseFrontmatterString(frontmatter.description ?? ""));
  if (!name || !description) {
    throw new Error(`browser-verifier source is missing required frontmatter fields: ${BROWSER_VERIFIER_SOURCE}`);
  }

  const toml = [
    "# GENERATED by scripts/build-codex.mjs from plugins/shape/agents/browser-verifier.md — do not hand-edit; re-run the generator.",
    `name = ${JSON.stringify(name)}`,
    `description = ${JSON.stringify(description)}`,
    "developer_instructions = '''",
    body,
    "'''",
    "",
  ].join("\n");

  mkdirSync(dirname(BROWSER_VERIFIER_DEST), { recursive: true });
  writeFileSync(BROWSER_VERIFIER_DEST, toml);
}

function buildHooks() {
  const sourceConfig = JSON.parse(readFileSync(CODEX_HOOKS_CONFIG_SOURCE, "utf8"));
  const mergedConfig = mergeOwnedSessionStartHook(
    existsSync(CODEX_HOOKS_CONFIG) ? JSON.parse(readFileSync(CODEX_HOOKS_CONFIG, "utf8")) : {},
    sourceConfig,
  );
  writeFileSync(CODEX_HOOKS_CONFIG, `${JSON.stringify(mergedConfig, null, 2)}\n`);
  for (const file of walk(CODEX_HOOKS_SOURCE_DIR)) {
    if (file === CODEX_HOOKS_CONFIG_SOURCE) continue;
    const rel = file.slice(CODEX_HOOKS_SOURCE_DIR.length + 1);
    const dest = join(CODEX_HOOKS_DIR, rel);
    mkdirSync(dirname(dest), { recursive: true });
    cpSync(file, dest, { force: true });
  }
}

function mergeOwnedSessionStartHook(existingConfig, sourceConfig) {
  const merged = structuredClone(existingConfig && typeof existingConfig === "object" ? existingConfig : {});
  const mergedHooks = merged.hooks && typeof merged.hooks === "object" ? merged.hooks : {};
  const sourceHooks = sourceConfig?.hooks && typeof sourceConfig.hooks === "object" ? sourceConfig.hooks : {};
  merged.hooks = mergedHooks;

  for (const [eventName, sourceEntries] of Object.entries(sourceHooks)) {
    if (eventName !== "SessionStart") {
      if (!(eventName in mergedHooks)) mergedHooks[eventName] = sourceEntries;
      continue;
    }

    const existingEntries = Array.isArray(mergedHooks.SessionStart) ? mergedHooks.SessionStart : [];
    const ownedEntries = Array.isArray(sourceEntries) ? sourceEntries.filter(isOwnedSessionStartEntry) : [];
    const preserved = existingEntries
      .map(stripOwnedSessionStartHooks)
      .filter((entry) => entry !== null);
    mergedHooks.SessionStart = [...preserved, ...ownedEntries];
  }

  return merged;
}

function stripOwnedSessionStartHooks(entry) {
  if (!entry || typeof entry !== "object") return entry;
  if (!Array.isArray(entry.hooks)) return entry;

  const hooks = entry.hooks.filter(
    (hook) => !(hook?.type === "command" && hook?.command === SESSION_START_HOOK_COMMAND),
  );
  if (hooks.length === entry.hooks.length) return entry;
  if (hooks.length === 0) return null;
  return { ...entry, hooks };
}

function isOwnedSessionStartEntry(entry) {
  if (!entry || typeof entry !== "object") return false;
  if (!Array.isArray(entry.hooks)) return false;
  return entry.hooks.some(
    (hook) => hook?.type === "command" && hook?.command === SESSION_START_HOOK_COMMAND,
  );
}

function lowerBrowserVerifierDescription(description) {
  return description.replace(BROWSER_VERIFIER_DESCRIPTION_OLD, BROWSER_VERIFIER_DESCRIPTION_NEW);
}

function splitFrontmatter(text) {
  const match = text.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!match) throw new Error("Expected YAML frontmatter block");

  const [, rawFrontmatter, body] = match;
  const frontmatter = {};
  for (const line of rawFrontmatter.split("\n")) {
    const field = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (!field) continue;
    frontmatter[field[1]] = parseFrontmatterString(field[2].trim());
  }
  return { frontmatter, body: body.replace(/\s+$/, "") };
}

function* walk(dir) {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) yield* walk(p);
    else yield p;
  }
}

build();

if (process.argv.includes("--sync-global")) {
  syncGlobal();
}

function syncGlobal() {
  const HOME = process.env.HOME || process.env.USERPROFILE;
  if (!HOME) return;
  const globalDir = join(HOME, ".agents", "skills");
  if (!existsSync(globalDir)) {
    console.log(`\n→ Global directory ~/.agents/skills does not exist. Skipping global sync.`);
    return;
  }

  console.log(`\n→ Syncing to global directory: ${globalDir}`);
  const profileName = argValue("--profile") ?? "all";
  const available = PLUGINS.flatMap((plugin) =>
    readdirSync(join(PLUGINS_DIR, plugin, "skills"))
      .filter((skill) => existsSync(join(PLUGINS_DIR, plugin, "skills", skill, "SKILL.md")))
      .map((skill) => `${plugin}-${skill}`),
  ).sort();
  const selected = selectProfile(PROJECTION, profileName, available);
  const selectedSet = new Set(selected);
  const receiptPath = join(globalDir, ".skills-marketplace-codex.json");
  const previous = existsSync(receiptPath)
    ? JSON.parse(readFileSync(receiptPath, "utf8")).skills ?? []
    : [];
  for (const flat of available) {
    if (isGeneratedMarketplaceSkill(join(globalDir, flat, "SKILL.md"))) previous.push(flat);
  }

  for (const flat of new Set(previous)) {
    if (selectedSet.has(flat)) continue;
    const stale = join(globalDir, flat);
    if (existsSync(stale)) rmSync(stale, { recursive: true });
  }

  let syncedCount = 0;

  for (const plugin of PLUGINS) {
    const skillsDir = join(PLUGINS_DIR, plugin, "skills");
    if (!existsSync(skillsDir)) continue;
    for (const skill of readdirSync(skillsDir)) {
      const srcSkillDir = join(skillsDir, skill);
      if (!statSync(srcSkillDir).isDirectory()) continue;

      const flat = `${plugin}-${skill}`;
      if (!selectedSet.has(flat)) continue;

      // Copy the COMPILED Codex output (never raw Claude source) — both prefixed and any
      // unprefixed install target must read from .agents/skills/, which already went through
      // the full lowering pipeline above.
      const compiledSkillDir = join(OUT_DIR, flat);
      const destPrefixedDir = join(globalDir, flat);
      if (existsSync(compiledSkillDir)) {
        if (existsSync(destPrefixedDir)) rmSync(destPrefixedDir, { recursive: true });
        cpSync(compiledSkillDir, destPrefixedDir, { recursive: true });
        syncedCount++;
      }
    }
  }
  writeFileSync(receiptPath, `${JSON.stringify({ profile: profileName, skills: selected }, null, 2)}\n`);
  console.log(`✓ Synced ${syncedCount} compiled skills with Codex profile "${profileName}".`);
  console.log("✓ Unprefixed Claude-source skills were not copied; Codex installs only the compiled names.");

  if (process.argv.includes("--dedupe-global-roots")) {
    const legacyRoot = join(HOME, ".codex", "skills");
    let removed = 0;
    for (const flat of available) {
      const legacyDir = join(legacyRoot, flat);
      if (!isGeneratedMarketplaceSkill(join(legacyDir, "SKILL.md"))) continue;
      rmSync(legacyDir, { recursive: true });
      removed++;
    }
    console.log(`✓ Removed ${removed} generated duplicate marketplace skills from ~/.codex/skills.`);
  }

  const copies = findInstalledSkillCopies(HOME, selected);
  const duplicates = [...copies.entries()].filter(([, paths]) => paths.length > 1);
  if (duplicates.length) {
    console.warn("\n⚠ Duplicate Codex skill copies remain across ~/.agents/skills and ~/.codex/skills:");
    for (const [name, paths] of duplicates) console.warn(`  ${name}: ${paths.join(" · ")}`);
    console.warn("  Re-run with --dedupe-global-roots to remove generated marketplace duplicates.");
  }
}

function argValue(flag) {
  const index = process.argv.indexOf(flag);
  return index === -1 ? null : process.argv[index + 1] ?? null;
}

function isGeneratedMarketplaceSkill(skillMd) {
  if (!existsSync(skillMd)) return false;
  return readFileSync(skillMd, "utf8").includes(
    "GENERATED by scripts/build-codex.mjs from plugins/",
  );
}
