#!/usr/bin/env node
/**
 * build-codex.mjs — one-way generator: Claude Code plugin skills → Codex Agent Skills (★).
 *
 * The Claude plugins under `plugins/<p>/skills/<s>/` are the SINGLE SOURCE OF TRUTH.
 * This script emits a Codex-discoverable mirror under `.agents/skills/<p>-<s>/` plus a
 * repo-root `AGENTS.md` synthesised from plugin `CLAUDE.md` files. Re-run after any
 * skill edit; never hand-edit the generated output (it is overwritten).
 *
 * Codex's skill format IS the Agent Skills format (SKILL.md: name+description frontmatter +
 * body + optional references/), so the transform is mechanical: flatten the plugin namespace
 * (`nav:audit` → `nav-audit`, since Codex skills are flat + unnamespaced), rewrite cross-skill
 * and CLAUDE.md references, and re-root bundled reference paths to travel with each skill dir.
 *
 * Reads: node:fs · node:path (plugins/ tree · plugins/<p>/CLAUDE.md)
 */
import { readFileSync, writeFileSync, readdirSync, mkdirSync, rmSync, existsSync, statSync, cpSync } from "node:fs";
import { join, dirname, basename } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const PLUGINS_DIR = join(ROOT, "plugins");
const OUT_DIR = join(ROOT, ".agents", "skills");
const AGENTS_MD = join(ROOT, "AGENTS.md");

const PLUGINS = readdirSync(PLUGINS_DIR)
  .filter((plugin) => {
    const pluginDir = join(PLUGINS_DIR, plugin);
    return (
      statSync(pluginDir).isDirectory() &&
      existsSync(join(pluginDir, "CLAUDE.md")) &&
      existsSync(join(pluginDir, "skills"))
    );
  })
  .sort();
const SKILLS = [
  ...new Set(
    PLUGINS.flatMap((plugin) =>
      readdirSync(join(PLUGINS_DIR, plugin, "skills")).filter((skill) =>
        statSync(join(PLUGINS_DIR, plugin, "skills", skill)).isDirectory(),
      ),
    ),
  ),
].sort();
const PLUGIN_PATTERN = PLUGINS.map(escapeRegExp).join("|");
const SKILL_PATTERN = SKILLS.map(escapeRegExp).join("|");
// `/nav:audit`, `nav:audit`, `/shape:mockup` → `nav-audit` / `shape-mockup`. Requires a real
// verb after the colon, so bare-namespace prose ("the `nav:` namespace") is left untouched.
const NS = new RegExp(`/?\\b(${PLUGIN_PATTERN}):(${SKILL_PATTERN})\\b`, "g");
// Full skills-root reference paths → repo-root-relative `references/…` (they travel with the dir).
const REF_PATH = new RegExp(`plugins/(?:${PLUGIN_PATTERN})/skills/[^/]+/references/`, "g");
const PLUGIN_CLAUDE = new RegExp(`plugins/(?:${PLUGIN_PATTERN})/CLAUDE\\.md`, "g");
const CODEX_DESCRIPTION_BUDGET = 1000;

function escapeRegExp(text) {
  return text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/** Rewrites shared by both profiles: namespace flatten + plugin-CLAUDE.md → AGENTS.md. */
function rewriteCommon(text) {
  return text.replace(NS, "$1-$2").replace(PLUGIN_CLAUDE, "AGENTS.md");
}

/** Skill profile: also re-root bundled reference paths + generic "CLAUDE.md" → "AGENTS.md". */
function rewriteSkill(text) {
  return rewriteCommon(text).replace(REF_PATH, "references/").replace(/CLAUDE\.md/g, "AGENTS.md");
}

/** Bump the frontmatter `name:` to the flattened Codex name (first occurrence only). */
function renameFrontmatter(text, bare, flat) {
  return text.replace(new RegExp(`^name:\\s*${bare}\\s*$`, "m"), `name: ${flat}`);
}

/**
 * Codex validates skill metadata more strictly than Claude plugins do:
 * `description` must parse as YAML and must not exceed 1024 characters.
 */
function normalizeCodexFrontmatter(text) {
  return text.replace(/^---\n([\s\S]*?)\n---/, (_match, frontmatter) => {
    const normalized = frontmatter.replace(/^description:\s*(.*)$/m, (_line, rawDescription) => {
      let description = parseFrontmatterString(rawDescription.trim()).replace(/\s+/g, " ").trim();
      if (description.length > CODEX_DESCRIPTION_BUDGET) {
        description = `${description.slice(0, CODEX_DESCRIPTION_BUDGET - 3).trimEnd()}...`;
      }
      return `description: ${JSON.stringify(description)}`;
    });
    return `---\n${normalized}\n---`;
  });
}

function parseFrontmatterString(raw) {
  try {
    const parsed = JSON.parse(raw);
    return typeof parsed === "string" ? parsed : raw;
  } catch {
    return raw;
  }
}

const GEN_BANNER_SKILL = "<!-- GENERATED by scripts/build-codex.mjs from plugins/{plugin}/skills/{skill}/ — do not hand-edit; re-run the generator. -->\n";

function build() {
  if (existsSync(OUT_DIR)) rmSync(OUT_DIR, { recursive: true });
  mkdirSync(OUT_DIR, { recursive: true });

  const emitted = [];
  for (const plugin of PLUGINS) {
    const skillsDir = join(PLUGINS_DIR, plugin, "skills");
    if (!existsSync(skillsDir)) continue;
    for (const skill of readdirSync(skillsDir)) {
      const srcSkillDir = join(skillsDir, skill);
      if (!statSync(srcSkillDir).isDirectory()) continue;
      const srcSkillMd = join(srcSkillDir, "SKILL.md");
      if (!existsSync(srcSkillMd)) continue;

      const flat = `${plugin}-${skill}`;
      const outSkillDir = join(OUT_DIR, flat);
      mkdirSync(outSkillDir, { recursive: true });

      // SKILL.md: rename in frontmatter, rewrite refs, prepend generated banner after frontmatter.
      let md = readFileSync(srcSkillMd, "utf8");
      md = renameFrontmatter(md, skill, flat);
      md = rewriteSkill(md);
      md = normalizeCodexFrontmatter(md);
      const banner = GEN_BANNER_SKILL.replace("{plugin}", plugin).replace("{skill}", skill);
      md = md.replace(/^(---\n[\s\S]*?\n---\n)/, `$1${banner}`);
      writeFileSync(join(outSkillDir, "SKILL.md"), md);

      // Bundled resources (references/, assets/, scripts/): copy verbatim, rewriting *.md/*.html paths.
      for (const sub of ["references", "assets", "scripts"]) {
        const srcSub = join(srcSkillDir, sub);
        if (!existsSync(srcSub)) continue;
        const outSub = join(outSkillDir, sub);
        cpSync(srcSub, outSub, { recursive: true });
        for (const f of walk(outSub)) {
          if (/\.(md|html|txt)$/.test(f)) writeFileSync(f, rewriteSkill(readFileSync(f, "utf8")));
        }
      }
      emitted.push(flat);
    }
  }

  buildAgentsMd();
  console.log(`✓ ${emitted.length} Codex skills → .agents/skills/  (${emitted.join(", ")})`);
  console.log(`✓ AGENTS.md (from CLAUDE.md + ${PLUGINS.map((p) => `plugins/${p}/CLAUDE.md`).join(" + ")})`);
}

/** Synthesise repo-root AGENTS.md: the repo-root CLAUDE.md (repo-wide rules) + each plugin's CLAUDE.md. */
function buildAgentsMd() {
  const preamble = [
    "# AGENTS.md — `skills` marketplace",
    "",
    "<!-- GENERATED by scripts/build-codex.mjs from CLAUDE.md + plugins/*/CLAUDE.md — do not hand-edit; re-run the generator. -->",
    "",
    "> Context for an agent working in **this repo**. The source of truth is the Claude Code plugins under",
    "> `plugins/<plugin>/skills/<skill>/SKILL.md`. Their Codex mirror lives in `.agents/skills/<plugin>-<skill>/`",
    "> (flat, unnamespaced — Codex has no plugin namespace) and is **generated** by `scripts/build-codex.mjs`.",
    "> Edit the plugin skills, then re-run the generator; never hand-edit `.agents/skills/` or this file.",
    "",
    "Each `SKILL.md` is self-contained (it restates the rules it needs). The repo-wide rules for editing this",
    "marketplace follow (mirrored from the repo-root `CLAUDE.md`), then each plugin's own conventions.",
  ].join("\n");

  let rootRules = readFileSync(join(ROOT, "CLAUDE.md"), "utf8");
  rootRules = rewriteCommon(rootRules.replace(/^#\s+CLAUDE\.md.*$/m, "# marketplace — repo-wide rules (editing this repo)"));

  const sections = PLUGINS.map((plugin) => {
    let body = readFileSync(join(PLUGINS_DIR, plugin, "CLAUDE.md"), "utf8");
    body = body.replace(/^#\s+.*plugin-level CLAUDE\.md\s*$/m, `# ${plugin} — plugin conventions`);
    return rewriteCommon(body);
  });

  writeFileSync(AGENTS_MD, [preamble, rootRules, ...sections].join("\n\n---\n\n") + "\n");
}

function* walk(dir) {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) yield* walk(p);
    else yield p;
  }
}

build();

if (process.argv.includes("--sync-global")) {
  syncGlobal();
}

function syncGlobal() {
  const HOME = process.env.HOME || process.env.USERPROFILE;
  if (!HOME) return;
  const globalDir = join(HOME, ".agents", "skills");
  if (!existsSync(globalDir)) {
    console.log(`\n→ Global directory ~/.agents/skills does not exist. Skipping global sync.`);
    return;
  }

  console.log(`\n→ Syncing to global directory: ${globalDir}`);
  let prefixedCount = 0;
  let unprefixedCount = 0;

  for (const plugin of PLUGINS) {
    const skillsDir = join(PLUGINS_DIR, plugin, "skills");
    if (!existsSync(skillsDir)) continue;
    for (const skill of readdirSync(skillsDir)) {
      const srcSkillDir = join(skillsDir, skill);
      if (!statSync(srcSkillDir).isDirectory()) continue;

      const flat = `${plugin}-${skill}`;
      const srcSkillMd = join(srcSkillDir, "SKILL.md");

      // 1. Copy prefixed compiled skill (from .agents/skills/ flat mirror)
      const compiledSkillDir = join(OUT_DIR, flat);
      const destPrefixedDir = join(globalDir, flat);
      if (existsSync(compiledSkillDir)) {
        if (existsSync(destPrefixedDir)) rmSync(destPrefixedDir, { recursive: true });
        cpSync(compiledSkillDir, destPrefixedDir, { recursive: true });
        prefixedCount++;
      }

      // 2. Overwrite un-prefixed skill if it exists globally (from agy install)
      const destUnprefixedDir = join(globalDir, skill);
      const destUnprefixedMd = join(destUnprefixedDir, "SKILL.md");
      if (existsSync(destUnprefixedDir) && existsSync(srcSkillMd)) {
        cpSync(srcSkillMd, destUnprefixedMd);
        unprefixedCount++;
      }
    }
  }
  console.log(`✓ Synced ${prefixedCount} prefixed skills and updated ${unprefixedCount} un-prefixed global skills.`);
}
